version: "3"

services:
  server: 
    environment: 
      - TZ=America/Toronto
    image: ghcr.io/jjcazau/ember-scanner:latest
    ports:
      - "3000:3000"
    volumes:
      - /home/radio/ember-scanner:/app/data:z